// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: proto/url_shortening.proto

package url

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UrlShorteningService_CreateUrl_FullMethodName = "/url.UrlShorteningService/CreateUrl"
	UrlShorteningService_AccessUrl_FullMethodName = "/url.UrlShorteningService/AccessUrl"
)

// UrlShorteningServiceClient is the client API for UrlShorteningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlShorteningServiceClient interface {
	CreateUrl(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error)
	AccessUrl(ctx context.Context, in *AccessUrlRequest, opts ...grpc.CallOption) (*AccessUrlResponse, error)
}

type urlShorteningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShorteningServiceClient(cc grpc.ClientConnInterface) UrlShorteningServiceClient {
	return &urlShorteningServiceClient{cc}
}

func (c *urlShorteningServiceClient) CreateUrl(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error) {
	out := new(CreateUrlResponse)
	err := c.cc.Invoke(ctx, UrlShorteningService_CreateUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShorteningServiceClient) AccessUrl(ctx context.Context, in *AccessUrlRequest, opts ...grpc.CallOption) (*AccessUrlResponse, error) {
	out := new(AccessUrlResponse)
	err := c.cc.Invoke(ctx, UrlShorteningService_AccessUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShorteningServiceServer is the server API for UrlShorteningService service.
// All implementations must embed UnimplementedUrlShorteningServiceServer
// for forward compatibility
type UrlShorteningServiceServer interface {
	CreateUrl(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error)
	AccessUrl(context.Context, *AccessUrlRequest) (*AccessUrlResponse, error)
	mustEmbedUnimplementedUrlShorteningServiceServer()
}

// UnimplementedUrlShorteningServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUrlShorteningServiceServer struct {
}

func (UnimplementedUrlShorteningServiceServer) CreateUrl(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUrl not implemented")
}
func (UnimplementedUrlShorteningServiceServer) AccessUrl(context.Context, *AccessUrlRequest) (*AccessUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessUrl not implemented")
}
func (UnimplementedUrlShorteningServiceServer) mustEmbedUnimplementedUrlShorteningServiceServer() {}

// UnsafeUrlShorteningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlShorteningServiceServer will
// result in compilation errors.
type UnsafeUrlShorteningServiceServer interface {
	mustEmbedUnimplementedUrlShorteningServiceServer()
}

func RegisterUrlShorteningServiceServer(s grpc.ServiceRegistrar, srv UrlShorteningServiceServer) {
	s.RegisterService(&UrlShorteningService_ServiceDesc, srv)
}

func _UrlShorteningService_CreateUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShorteningServiceServer).CreateUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShorteningService_CreateUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShorteningServiceServer).CreateUrl(ctx, req.(*CreateUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShorteningService_AccessUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShorteningServiceServer).AccessUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShorteningService_AccessUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShorteningServiceServer).AccessUrl(ctx, req.(*AccessUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlShorteningService_ServiceDesc is the grpc.ServiceDesc for UrlShorteningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlShorteningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "url.UrlShorteningService",
	HandlerType: (*UrlShorteningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUrl",
			Handler:    _UrlShorteningService_CreateUrl_Handler,
		},
		{
			MethodName: "AccessUrl",
			Handler:    _UrlShorteningService_AccessUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/url_shortening.proto",
}
